handdetect:
  model_path: "backend/src/models/handdetection/model/hand_landmarker.task"
  max_hands: 1
  threshold: 0.5
  tracking_threshold: 0.5

gesturedetect:
  model_path: "backend/src/models/handdetection/model/gesture_recognizer.task"
  max_hands: 1
  threshold: 0.5
  tracking_threshold: 0.5