stt:
  model_id: "openai/whisper-small"
  model_path: "backend/src/models/speech/model"
  samplerate: 16000
  blocksize: 8000
  channels: 1
  dtype: "int16"
  chunk_duration: 3
  language: "german"
  task: "translate"
  local: True
  optim:
    torch_dtype: auto
    attn_implementation: sdpa
    channels_last: false
    compile: false
    compile_mode: reduce-overhead
